### ISSUE TITLE
Requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by pabl-o-ce** [CodeSleeve/asset-pipeline#140]
"require": {
        "laravel/framework": "4.1.*",
        "codesleeve/asset-pipeline": "dev-master"
    },
<strong>cmd</strong>
c:\project-name><strong>composer update</strong>
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  <strong>Problem 1</strong>
    - Installation request for codesleeve/asset-pipeline dev-master@dev -> satis
fiable by codesleeve/asset-pipeline[dev-master].
    - codesleeve/asset-pipeline dev-master requires ext-fileinfo \* -><strong> the reques
ted PHP extension fileinfo is missing from your system.</strong>

I dont know what is going on?
help!

**Comment by drewstaylor** [comment]
I also have fileinfo module enabled and my composer install is still throwing this error:
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codesleeve/asset-pipeline dev-master -> satisfiable by codesleeve/asset-pipeline[dev-master].
    - codesleeve/asset-pipeline dev-master requires ext-fileinfo \* -> the requested PHP extension fileinfo is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - /usr/local/lib/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
