### ISSUE TITLE
PNG image on production is broken

### ISSUE THREAD

**Issue by harrygr** [CodeSleeve/asset-pipeline#219]
Works fine locally. Production environment runs nginx and other assets load, including jpegs.

PNG image loads with 200 OK status but shows browsers "broken image" icon. E.g. https://art.ipscap.com/assets/select2.png

SO help question opened here: http://stackoverflow.com/questions/26525311/broken-png-image-using-laravel-asset-pipeline-despite-200-ok-status

**Comment by Braunson** [comment]
:+1: Same issue here, the png won't display but when trying to access it directly, it force downloads and is not readable as an image.
